# Site settings
title: Let Me Write...
email: prnawa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Let me write down my thoughts and experiences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://prnawa.github.io/" # the base hostname & protocol for your site
twitter_username: prnawa
github_username:  prnawa

# Build settings
markdown: kramdown
